use bootstrap-tab-history to pop tab switches onto history
ElixirTeSS/TeSS pull request #878
Opened 2023-08-01 13:07 UTC by DaanVanVugt

**Summary of changes**

- Automatically switch to anchored tags on load
- Push tab switches onto history

**Motivation and context**

I'd like to be able to deeplink to the calendar / map views

Note that we'd need to update that tab since it only loads the calendar once we click (and I expect the map to behave the same?)
 
**Screenshots**

**Checklist**

- [x] I have read and followed the [CONTRIBUTING](https://github.com/ElixirTeSS/TeSS/blob/master/CONTRIBUTING.md) guide.
- [x] I confirm that I have the authority necessary to make this contribution on behalf of its copyright owner and agree
  to license it to the TeSS codebase under the 
  [BSD license](https://github.com/ElixirTeSS/TeSS/blob/master/LICENSE).

2023-08-01 14:34 UTC, fbacall reviewed
Does this still avoid #671 ?

We used to have a tab memory feature but it did not behave well with turbolinks

2023-08-01 14:57 UTC, DaanVanVugt commented
This should add to the history set, so I don't think it would cause that problem.

I checked just now, but the search page does not use the `tab` helper so has no memory.

2023-08-02 09:20 UTC, fbacall commented on app/helpers/application_helper.rb
> +        options['data-tab-history-changer'] = 'push'
I think I prefer the default of "replace", so it does not fill up your history if you switch between tabs.

2023-08-02 09:20 UTC, fbacall requested changes
Looks good otherwise

2023-08-04 08:22 UTC, fbacall approved these changes

2023-08-04 08:22 UTC, merged